from typing import Any, List, Optional
from datetime import datetime
from .mixins import Hashable


class Role(Hashable):
    def __lt__(self, other: Any) -> bool: ...

    def __le__(self, other: Any) -> bool: ...

    def __gt__(self, other: Any) -> bool: ...

    def __ge__(self, other: Any) -> bool: ...

    @property
    def created_at(self) -> datetime: ...

    @property
    def mention(self) -> str: ...

    @property
    def members(self) -> List[Any]: ...

    async def edit(self, *, name: str, permissions: Any, colour: Any, hoist: bool, mentionable: bool,
                   position: int, reason: Optional[str] = ...) -> None: ...

    async def delete(self, *, reason: Optional[str] = ...) -> None: ...
