from typing import Any, Dict, Callable, Optional


class ClientResponse:
    def close(self) -> None: ...

    async def read(self) -> bytes: ...

    async def release(self) -> None: ...

    def raise_for_status(self) -> None: ...

    async def text(self, encoding: Optional[str] = ...) -> str: ...

    async def json(self, encoding: Optional[str] = ...,
                   loads: Callable[..., Any] = ...,
                   content_type: Optional[str] = ...) -> Dict[str, Any]: ...
