from typing import Any, Dict, Callable


class ClientResponse:
    def close(self) -> None: ...

    async def read(self) -> bytes: ...

    async def release(self) -> None: ...

    def raise_for_status(self) -> None: ...

    async def text(self, encoding: str = None) -> str: ...

    async def json(self, encoding: str = None,
                   loads: Callable[..., Any] = ...,
                   content_type: str = ...) -> Dict[str, Any]: ...
