"""Add tsvector columns

Revision ID: f343a13c8b35
Revises: 85d51f96a1cd
Create Date: 2022-08-01 11:11:23.162146

"""
import sqlalchemy as sa

from alembic import op
from erasmus.db.base import TSVector

# revision identifiers, used by Alembic.
revision = 'f343a13c8b35'
down_revision = '85d51f96a1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'confession_articles',
        sa.Column(
            'search_vector',
            TSVector(),
            sa.Computed(
                "to_tsvector('english', title || ' ' || text)",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        'confession_articles_search_idx',
        'confession_articles',
        ['search_vector'],
        unique=False,
        postgresql_using='gin',
    )
    op.add_column(
        'confession_questions',
        sa.Column(
            'search_vector',
            TSVector(),
            sa.Computed(
                "to_tsvector('english', question_text || ' ' || answer_text)",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        'confession_questions_search_idx',
        'confession_questions',
        ['search_vector'],
        unique=False,
        postgresql_using='gin',
    )
    # ### end Alembic commands ###

    op.drop_index(
        'confession_questions_text_idx',
        table_name='confession_questions',
        postgresql_using='gin',
    )
    op.drop_index(
        'confession_articles_text_idx',
        table_name='confession_articles',
        postgresql_using='gin',
    )


def downgrade():
    op.create_index(
        'confession_articles_text_idx',
        'confession_articles',
        [sa.text("to_tsvector('english', text)")],
        postgresql_using='gin',
    )
    op.create_index(
        'confession_questions_text_idx',
        'confession_questions',
        [sa.text("to_tsvector('english', question_text || ' ' || answer_text)")],
        postgresql_using='gin',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'confession_questions_search_idx',
        table_name='confession_questions',
        postgresql_using='gin',
    )
    op.drop_column('confession_questions', 'search_vector')
    op.drop_index(
        'confession_articles_search_idx',
        table_name='confession_articles',
        postgresql_using='gin',
    )
    op.drop_column('confession_articles', 'search_vector')
    # ### end Alembic commands ###
