class ZoneinfoError(Exception): ...
class InvalidZoneinfoFile(ZoneinfoError): ...

class InvalidTimezone(ZoneinfoError):
    def __init__(self, name: str) -> None: ...

class InvalidPosixSpec(ZoneinfoError):
    def __init__(self, spec: str) -> None: ...
