def posix_spec(spec: str) -> PosixTimezone: ...

class PosixTransition:
    def __init__(self, offset: int) -> None: ...
    @property
    def offset(self) -> int: ...
    def trans_offset(self, is_leap: bool, jan1_weekday: int) -> int: ...

class JPosixTransition(PosixTransition):
    def __init__(self, day: int, offset: int) -> None: ...
    @property
    def day(self) -> int: ...
    def trans_offset(self, is_leap: bool, jan1_weekday: int) -> int: ...

class NPosixTransition(PosixTransition):
    def __init__(self, day: int, offset: int) -> None: ...
    @property
    def day(self) -> int: ...
    def trans_offset(self, is_leap: bool, jan1_weekday: int) -> int: ...

class MPosixTransition(PosixTransition):
    def __init__(self, month: int, week: int, weekday: int, offset: int) -> None: ...
    @property
    def month(self) -> int: ...
    @property
    def week(self) -> int: ...
    @property
    def weekday(self) -> int: ...
    def trans_offset(self, is_leap: bool, jan1_weekday: int) -> int: ...

class PosixTimezone:
    def __init__(
        self,
        std_abbr: str,
        std_offset: int,
        dst_abbr: str | None,
        dst_offset: int | None,
        dst_start: PosixTransition | None = ...,
        dst_end: PosixTransition | None = ...,
    ) -> None: ...
    @property
    def std_abbr(self) -> str: ...
    @property
    def std_offset(self) -> int: ...
    @property
    def dst_abbr(self) -> str | None: ...
    @property
    def dst_offset(self) -> int | None: ...
    @property
    def dst_start(self) -> PosixTransition | None: ...
    @property
    def dst_end(self) -> PosixTransition | None: ...
