from _typeshed import StrOrBytesPath

from .timezone import Timezone

class Reader:
    def __init__(self, extend: bool = ...) -> None: ...
    def read_for(self, timezone: str) -> Timezone: ...
    def read(self, file_path: StrOrBytesPath | int) -> Timezone: ...
