from datetime import timedelta

class TransitionType:
    def __init__(self, offset: int, is_dst: bool, abbr: str) -> None: ...
    @property
    def offset(self) -> int: ...
    @property
    def abbreviation(self) -> str: ...
    def is_dst(self) -> bool: ...
    def utcoffset(self) -> timedelta: ...
