# Stubs for asyncpg.connresource (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def guarded(meth): ...

class ConnectionResource:
    def __init__(self, connection) -> None: ...
