# Stubs for asyncpg.protocol (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .protocol import NO_TIMEOUT as NO_TIMEOUT, Protocol as Protocol, Record as Record

__all__ = ('NO_TIMEOUT', 'Protocol', 'Record')
